name: shadow_hand
description: A new Flutter project.


publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"


dependencies:
  flutter:
    sdk: flutter
  
  # flip_card: ^0.6.0

  playing_cards: ^0.3.1+9

  provider: ^5.0.0

  # local_hero: ^0.2.0

  web_socket_channel: ^2.1.0

  cupertino_icons: ^1.0.2

  patterns_canvas: ^0.4.0

  http: ^0.13.5
  shared_preferences: ^2.0.15
  rename_app: ^1.1.0
  flutter_gen: ^5.3.1
  build_runner: ^2.3.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  flutter_gen_runner:
  flutter_launcher_icons: 



flutter:
  
  uses-material-design: true

  assets:
    - assets/
